# Generated by Django 4.2.7 on 2023-12-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='genres',
            field=models.CharField(default='unspecified', max_length=300),
        ),
    ]
