# Generated by Django 4.2.7 on 2023-12-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_moviedata_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='Images/None/NoImg.jpg', upload_to='Images/'),
        ),
    ]
